### ISSUE TITLE
questões acerca do trabalho

### ISSUE THREAD

**Issue by 38224** [isel-leic-ls/1415-2-common#10]
bom dia, 
Vim por este meio pedir algumas informações adicionais de forma a 
corresponder ás suas expectativas em relação ao trabalho proposto. 

Vou ser sucinto: 

-pode haver coordenadores sem unidade curricular? 
-pode haver unidades curriculares sem coordenador? 
-uma unidade curricular tem de ter uma turma associada? 
-como um grupo é um conjunto de 1 ou mais elementos, não poderá haver 
grupos vazios, é essa a sua intenção? 
-um aluno pode pertencer a mais do que um grupo para a mesma turma? 
-qual a escala do numero de aluno e professor? 
-um grupo tem limite maximo de alunos?

**Comment by pmhsfelix** [comment]
respostas inline

-pode haver coordenadores sem unidade curricular? 
Não existe o conceito de coordenador
-pode haver unidades curriculares sem coordenador? 
Não
-uma unidade curricular tem de ter uma turma associada? 
Não
-como um grupo é um conjunto de 1 ou mais elementos, não poderá haver 
grupos vazios, é essa a sua intenção? 
Não podem existir grupos vazios
-um aluno pode pertencer a mais do que um grupo para a mesma turma? 
Não
-qual a escala do numero de aluno e professor? 
Número natural
-um grupo tem limite maximo de alunos?
Sim, definido por turma
