### ISSUE TITLE
Phase 2 demo

### ISSUE THREAD

**Issue by joanafcoelho** [isel-leic-ls/1415-2-common#12]
Relativamente a esta alínea do guião: 
8-List courses directly from the console. Ensure the application ends after showing an empty list.

Só quando no caso dos courses é que se a lista vier vazia o programa termina, ou é em qualquer caso?

**Comment by pmhsfelix** [comment]
Se os parâmetros forem passados na linha de comando, a aplicação deve realizar apenas um comando e terminar sempre, independentemente da execução resultar em erro ou não.

**Comment by GoncaloDomingues** [comment]
No caso de tentar obter resultados e a lista vier vazia em qualquer um dos comandos o programa termina? ou so no caso dos courses?
