### ISSUE TITLE
Phase 2 demo

### ISSUE THREAD

**Issue by andrelupe** [isel-leic-ls/1415-2-common#13]
23-Create new groups without students on "1415v-D1" and "1415v-N1". Ensure both groups have the number 1.

Temos dúvidas relativamente a esta questão, porque segundo os comandos existentes não é possível criar grupos sem pelo menos um estudante.

**Comment by pmhsfelix** [comment]
O parâmetro numStu pode ocorrer zero ou mais vezes, i.e., deve ser possível criar um grupo sem alunos.
