### ISSUE TITLE
phase2 - demo

### ISSUE THREAD

**Issue by GoncaloDomingues** [isel-leic-ls/1415-2-common#14]
No caso de tentar obter resultados e a lista vier vazia em qualquer um dos comandos o programa termina? ou so no caso dos courses?

**Comment by pmhsfelix** [comment]
Se os parâmetros forem definidos na linha de comando, a aplicação realiza apenas um comando e termina. Caso contrário, a aplicação só deve acabar na execução do comando EXIT.
