### ISSUE TITLE
duvida comando Graph

### ISSUE THREAD

**Issue by GoncaloDomingues** [isel-leic-ls/1415-2-common#18]
Boa tarde, 

O que é suposto aparecer no comando GetCoursesAcrClassesSemNumGroupsGno? Seria suposto apresentar os detalhes do grupo, tal como os seu elementos? Porém os elementos serão apresentados no GetCoursesAcrClassesSemNumGroupsGnoStudents. 

Obrigado

**Comment by pmhsfelix** [comment]
Sim, é suposto apresentar os detalhes do grupo. Como actualmente a única informação de um grupo são os seus elementos, é natural que ambos os comandos retornem informação semelhante.
