### ISSUE TITLE
Sem acesso

### ISSUE THREAD

**Issue by LuisPMNeves** [isel-leic-ls/1415-2-common#2]
Boa tarde
Não tenho acesso ao repositório privado de grupo.

**Comment by pmhsfelix** [comment]
Qual é a turma e grupo?

**Comment by LuisPMNeves** [comment]
Grupo 5

**Comment by pmhsfelix** [comment]
Convite para acesso ao repositório enviado. Reabrir se o problema não ficar resolvido.
