### ISSUE TITLE
Sem acesso

### ISSUE THREAD

**Issue by edgaralves33017** [isel-leic-ls/1415-2-common#4]
Boa noite,
Não tenho acesso ao repositório de grupo. Pertenço ao grupo 5 da turma LI41N.

**Comment by pmhsfelix** [comment]
Foi enviado um convite para a conta de email associada à sua conta Github. Tem de aceitar o convite antes de conseguir aceder. Por favor, reabra este ticket caso continue sem conseguir aceder.

**Comment by edgaralves33017** [comment]
Boa noite,

Até agora, não recebi o convite.
